spring.application.name=quizApp
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/quiz
spring.datasource.username=root
spring.datasource.password=Alaf@1234*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true